### ISSUE TITLE
Write functionality for local cache and make it available everywhere on the site

### ISSUE THREAD

**Issue by petterrostrup** [petterrostrup/drunkSouls#27]

**Comment by aleksamd** [comment]
- _Dette må researches. Husk at safari ikke støtter service workers. Og chrome på apple-enheter er bare en reskin av safari_

Edit: Dette er en javascript-ting og burde funke

**Comment by petterrostrup** [comment]
Blir vel bare browser-cache i første omgang som er tenkt her. Vi får se hvordan vi kan cache ting på klienten over lengre tid på en senere issue

**Comment by petterrostrup** [comment]
Så en alminnelig browser-cache med levetid på et døgn kanskje? Der det som caches blir verdiene for hver sin-counter?
